FROM node:18.17.1-alpine as build

ARG PORT
ARG host
ARG server
ARG DB_USER
ARG DB_PWD
ARG DB_SCHEMA
ARG SECRET_ODF_KEY
ARG ALGORITH_ENCRYPTED
ARG IV
ARG ROOT_DIR
ARG STATIC_DIST
ARG MS_COLUMN_DESCRIPTION_MOTIVES_POINT
ARG MS_TABLE_STORAGE_POINTED_HISTORIC
ARG ROWS_TO_INSERT_ON_STORAGE_POINTED_HISTORIC
ARG ROW_OF_STATUS_IN_STORAGE_POINTED_HISTORIC
ARG MS_TABLE_CONTAINER_OF_REWORK_ODFS
ARG COLUMN_OF_CONTAINER_OF_REWORK_ODF
ARG COLUMN_OF_CONTAINER_OF_REWORK_ODF
ARG MS_COLUMN_OF_FOR_ODF_CONDITION
ARG MS_COLUMN_OF_FOR_ODF_NUMBER_CONDITION
ARG MS_COLUMN_OF_FOR_ODF_OPERATION_NUMBER_CONDITION
ARG MS_COLUMN_OF_FOR_CHILD_PARTS_CONDITION
ARG MS_COLUMN_FOR_ODF_QUANTITY
ARG MS_TABLE_CONTAINER_OF_ALL_ODFS
ARG MS_TABLE_OF_ADDRESS
ARG MS_COLUMN_OF_ADDRESS_QUANTITY
ARG MS_TABLE_CONTAINER_OF_PARTS_STORAGE
ARG MS_COLUMN_CONTAINER_OF_PARTS_STORAGE
ARG MS_COLUMN_CONTAINER_OF_PARTS_WHERE_CONDITION
ARG MS_TABLE_CONTAINER_OF_RESERVATION
ARG MS_COLUMN_OF_EMPLOYEE_NAME
ARG MS_COLUMN_OF_EMPLOYEE_BAGDE
ARG MS_TABLE_CONTAINER_OF_ALL_EMPLOYEES
ARG MS_TABLE_CONTAINER_OF_SUPERVISORS
ARG MS_COLUMN_OF_MOTIVES
ARG MS_TABLE_CONTAINER_OF_RETURN_MOTIVES
ARG MS_TABLE_CONTAINER_OF_BAD_FEED_MOTIVES
ARG MS_TABLE_CONTAINER_OF_STOP_MOTIVES
ARG MS_TABLE_CONTAINER_OF_DRAWINGS
ARG MS_COLUMN_OF_PART_FOR_DRAWING
ARG MS_COLUMN_OF_PART_FOR_IMG_BLOP
ARG MS_COLUMN_OF_STAGE_ODF

ENV PORT ${PORT}
ENV host ${host}
ENV server ${server}
ENV DB_USER ${DB_USER}
ENV DB_PWD ${DB_PWD}
ENV DB_SCHEMA ${DB_SCHEMA}
ENV SECRET_ODF_KEY ${SECRET_ODF_KEY}
ENV ALGORITH_ENCRYPTED ${ALGORITH_ENCRYPTED}
ENV IV ${IV}
ENV ROOT_DIR ${ROOT_DIR}
ENV STATIC_DIST ${STATIC_DIST}
ENV MS_COLUMN_DESCRIPTION_MOTIVES_POINT ${MS_COLUMN_DESCRIPTION_MOTIVES_POINT} 
ENV MS_TABLE_STORAGE_POINTED_HISTORIC ${MS_TABLE_STORAGE_POINTED_HISTORIC} 
ENV ROWS_TO_INSERT_ON_STORAGE_POINTED_HISTORIC ${ROWS_TO_INSERT_ON_STORAGE_POINTED_HISTORIC} 
ENV ROW_OF_STATUS_IN_STORAGE_POINTED_HISTORIC ${ROW_OF_STATUS_IN_STORAGE_POINTED_HISTORIC} 
ENV MS_TABLE_CONTAINER_OF_REWORK_ODFS ${MS_TABLE_CONTAINER_OF_REWORK_ODFS} 
ENV COLUMN_OF_CONTAINER_OF_REWORK_ODF ${COLUMN_OF_CONTAINER_OF_REWORK_ODF} 
ENV COLUMN_OF_CONTAINER_OF_REWORK_ODF ${COLUMN_OF_CONTAINER_OF_REWORK_ODF} 
ENV MS_COLUMN_OF_FOR_ODF_CONDITION ${MS_COLUMN_OF_FOR_ODF_CONDITION} 
ENV MS_COLUMN_OF_FOR_ODF_NUMBER_CONDITION ${MS_COLUMN_OF_FOR_ODF_NUMBER_CONDITION} 
ENV MS_COLUMN_OF_FOR_ODF_OPERATION_NUMBER_CONDITION ${MS_COLUMN_OF_FOR_ODF_OPERATION_NUMBER_CONDITION} 
ENV MS_COLUMN_OF_FOR_CHILD_PARTS_CONDITION ${MS_COLUMN_OF_FOR_CHILD_PARTS_CONDITION} 
ENV MS_COLUMN_FOR_ODF_QUANTITY ${MS_COLUMN_FOR_ODF_QUANTITY} 
ENV MS_TABLE_CONTAINER_OF_ALL_ODFS ${MS_TABLE_CONTAINER_OF_ALL_ODFS} 
ENV MS_TABLE_OF_ADDRESS ${MS_TABLE_OF_ADDRESS} 
ENV MS_COLUMN_OF_ADDRESS_QUANTITY ${MS_COLUMN_OF_ADDRESS_QUANTITY} 
ENV MS_TABLE_CONTAINER_OF_PARTS_STORAGE ${MS_TABLE_CONTAINER_OF_PARTS_STORAGE} 
ENV MS_COLUMN_CONTAINER_OF_PARTS_STORAGE ${MS_COLUMN_CONTAINER_OF_PARTS_STORAGE} 
ENV MS_COLUMN_CONTAINER_OF_PARTS_WHERE_CONDITION ${MS_COLUMN_CONTAINER_OF_PARTS_WHERE_CONDITION} 
ENV MS_TABLE_CONTAINER_OF_RESERVATION ${MS_TABLE_CONTAINER_OF_RESERVATION} 
ENV MS_COLUMN_OF_EMPLOYEE_NAME ${MS_COLUMN_OF_EMPLOYEE_NAME} 
ENV MS_COLUMN_OF_EMPLOYEE_BAGDE ${MS_COLUMN_OF_EMPLOYEE_BAGDE} 
ENV MS_TABLE_CONTAINER_OF_ALL_EMPLOYEES ${MS_TABLE_CONTAINER_OF_ALL_EMPLOYEES} 
ENV MS_TABLE_CONTAINER_OF_SUPERVISORS ${MS_TABLE_CONTAINER_OF_SUPERVISORS} 
ENV MS_COLUMN_OF_MOTIVES ${MS_COLUMN_OF_MOTIVES} 
ENV MS_TABLE_CONTAINER_OF_RETURN_MOTIVES ${MS_TABLE_CONTAINER_OF_RETURN_MOTIVES} 
ENV MS_TABLE_CONTAINER_OF_BAD_FEED_MOTIVES ${MS_TABLE_CONTAINER_OF_BAD_FEED_MOTIVES} 
ENV MS_TABLE_CONTAINER_OF_STOP_MOTIVES ${MS_TABLE_CONTAINER_OF_STOP_MOTIVES} 
ENV MS_TABLE_CONTAINER_OF_DRAWINGS ${MS_TABLE_CONTAINER_OF_DRAWINGS} 
ENV MS_COLUMN_OF_PART_FOR_DRAWING ${MS_COLUMN_OF_PART_FOR_DRAWING} 
ENV MS_COLUMN_OF_PART_FOR_IMG_BLOP ${MS_COLUMN_OF_PART_FOR_IMG_BLOP} 
ENV MS_COLUMN_OF_STAGE_ODF ${MS_COLUMN_OF_STAGE_ODF} 

WORKDIR /server

COPY . .
COPY package.json ./
COPY tsconfig.json ./
COPY ecosystem.config.js ./

RUN npm install

RUN npm run tsc

EXPOSE ${PORT}

CMD ["npm", "run", "start"]
